#' Crea el esquema SQL
#' @noRd
create_schema <- function() {
  con <- censo_conectar()

  # HOGAR ----

  DBI::dbSendQuery(con, "DROP TABLE IF EXISTS HOGAR")

  DBI::dbSendQuery(
    con,
    "CREATE TABLE HOGAR (
    HOGAR_REF_ID INTEGER NOT NULL,
    VIVIENDA_REF_ID INTEGER NULL,
    NHOG INTEGER NULL,
    H05 INTEGER NULL,
    H06 INTEGER NULL,
    H07 INTEGER NULL,
    H08 INTEGER NULL,
    H09 INTEGER NULL,
    H10 INTEGER NULL,
    H11 INTEGER NULL,
    H12 INTEGER NULL,
    H13 INTEGER NULL,
    H14 INTEGER NULL,
    H15 INTEGER NULL,
    H16 INTEGER NULL,
    H19A INTEGER NULL,
    H19B INTEGER NULL,
    H19C INTEGER NULL,
    H19D INTEGER NULL,
    PROP INTEGER NULL,
    INDHAC INTEGER NULL,
    TOTPERS INTEGER NULL,
    ALGUNBI INTEGER NULL)"
  )

  # PERSONA ----

  DBI::dbSendQuery(con, "DROP TABLE IF EXISTS PEROSONA")

  DBI::dbSendQuery(
    con,
    "CREATE TABLE PERSONA (
	PERSONA_REF_ID INTEGER NOT NULL,
	HOGAR_REF_ID INTEGER NULL,
	personan INTEGER NULL,
	P01 INTEGER NULL,
	P02 INTEGER NULL,
	P03 INTEGER NULL,
	P05 INTEGER NULL,
	P07 INTEGER NULL,
	P12 INTEGER NULL,
	EDADAGRU INTEGER NULL,
	EDADQUI INTEGER NULL,
	P08 INTEGER NULL,
	P09 INTEGER NULL,
	P10 INTEGER NULL,
	CONDACT INTEGER NULL)"
  )

  # PROV ----

  DBI::dbSendQuery(con, "DROP TABLE IF EXISTS PROV")

  DBI::dbSendQuery(
    con,
    "CREATE TABLE PROV (
	PROV_REF_ID INTEGER NULL,
	CPV2010_REF_ID INTEGER NULL,
	IDPROV INTEGER NULL,
	PROV VARCHAR(3) NOT NULL,
	NOMPROV VARCHAR NULL)"
  )

  # DPTO ----

  DBI::dbSendQuery(con, "DROP TABLE IF EXISTS DPTO")

  DBI::dbSendQuery(
    con,
    "CREATE TABLE DPTO (
    DPTO_REF_ID INTEGER NOT NULL,
    PROV_REF_ID INTEGER NULL,
    IDDPTO VARCHAR NULL,
    DPTO VARCHAR(2) NOT NULL,
    NOMDPTO VARCHAR NULL)"
  )


  # FRAC ----

  DBI::dbSendQuery(con, "DROP TABLE IF EXISTS FRAC")

  DBI::dbSendQuery(
    con,
    "CREATE TABLE FRAC (
    FRAC_REF_ID INTEGER NOT NULL,
    DPTO_REF_ID INTEGER NULL,
    IDFRAC VARCHAR NULL)"
  )

  # RADIO ----

  DBI::dbSendQuery(con, "DROP TABLE IF EXISTS RADIO")

  DBI::dbSendQuery(
    con,
    "CREATE TABLE RADIO (
    RADIO_REF_ID INTEGER NOT NULL,
    FRAC_REF_ID INTEGER NULL,
    IDRADIO  VARCHAR NULL)"
  )



  # VIVIENDA ----

  DBI::dbSendQuery(con, "DROP TABLE IF EXISTS VIVIENDA")

  DBI::dbSendQuery(
    con,
    "CREATE TABLE VIVIENDA (
	VIVIENDA_REF_ID INTEGER NOT NULL,
	RADIO_REF_ID INTEGER NULL,
	TIPVV INTEGER NULL,
	V01 INTEGER NULL,
	V02 INTEGER NULL,
	V00 INTEGER NULL,
	URP INTEGER NULL,
	INCALSERV INTEGER NULL,
	INMAT INTEGER NULL,
	MUNI INTEGER NULL,
	LOCAL INTEGER NULL,
	INCALCONS INTEGER NULL,
	TOTHOG DOUBLE NULL)"
  )

  # metadatos ----

  DBI::dbSendQuery(con, "DROP TABLE IF EXISTS metadatos")

  DBI::dbSendQuery(
    con,
    "CREATE TABLE metadatos (
	version_duckdb VARCHAR NOT NULL,
	fecha_modificacion VARCHAR NOT NULL)"
  )

  # variables ----

  DBI::dbSendQuery(con, "DROP TABLE IF EXISTS variables")

  DBI::dbSendQuery(
    con,
    "CREATE TABLE variables (
	tabla VARCHAR NULL,
	variable VARCHAR NULL,
  descripcion VARCHAR NULL,
  tipo VARCHAR NULL,
  rango VARCHAR NULL)"
  )

  DBI::dbSendQuery(con, "DROP TABLE IF EXISTS variables_codificacion")

  DBI::dbSendQuery(
    con,
    "CREATE TABLE variables_codificacion (
	tabla VARCHAR NULL,
	variable VARCHAR NULL,
	valor INTEGER NULL,
  descripcion VARCHAR NULL)"
  )


  # indexes ----

  DBI::dbSendQuery(con, "CREATE UNIQUE INDEX PERSONAS_PERSONA_REF_ID ON PERSONA (PERSONA_REF_ID)")
  DBI::dbSendQuery(con, "CREATE UNIQUE INDEX HOGARES_HOGAR_REF_ID ON HOGAR (HOGAR_REF_ID)")
  DBI::dbSendQuery(con, "CREATE UNIQUE INDEX VIVIENDAS_VIVIENDA_REF_ID ON VIVIENDA (VIVIENDA_REF_ID)")
  DBI::dbSendQuery(con, "CREATE UNIQUE INDEX FRACCIONES_FRAC_REF_ID ON FRAC (FRAC_REF_ID)")
  DBI::dbSendQuery(con, "CREATE UNIQUE INDEX RADIOS_RADIO_REF_ID ON RADIO (RADIO_REF_ID)")
  DBI::dbSendQuery(con, "CREATE UNIQUE INDEX DEPTOS_DPTO_REF_ID ON DPTO (DPTO_REF_ID)")
  DBI::dbSendQuery(con, "CREATE UNIQUE INDEX PROVS_PROV_REF_ID ON PROV (PROV_REF_ID)")


  # disconnect ----

  DBI::dbDisconnect(con, shutdown = TRUE)
  gc()
}
